name: Publish to WinGet

# Only run after the Arm Artifacts have been uploaded
on:
  workflow_run:
    workflows: ["Build Vim for Windows ARM (on Release)"]
    types: [completed]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: vim.vim.nightly
          installers-regex: 'gvim.*(x64|x86|arm64).exe$'
          token: ${{ secrets.WINGET_TOKEN }}
