name: Publish to WinGet

# Only run after the Arm Artifacts have been uploaded
on:
  workflow_run:
    workflows: ["Build Vim for Windows ARM (on Release)"]
    types: [completed]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Needed to fetch all tags

      - name: Get latest tag
        id: get-version
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latest_tag"
          echo "version=${latest_tag#v}" >> "$GITHUB_OUTPUT"
          echo "tag=${latest_tag}" >> "$GITHUB_OUTPUT"

      - name: Run winget-releaser
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: vim.vim.nightly
          installers-regex: 'gvim.*(x64|x86|arm64).exe$'
          version: ${{ steps.get-version.outputs.version }}
          release-tag: ${{ steps.get-version.outputs.tag }}
          token: ${{ secrets.WINGET_TOKEN }}
